In [1]:
print("OK")

OK


In [2]:
import pandas as pd
import numpy as np


In [3]:
from sklearn.impute import SimpleImputer  #Missing value handle 
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df=pd.read_csv("covid_toy.csv")
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2, random_state=43)

In [15]:
x_train.head()

,age,gender,fever,cough,city
44,20,Male,102.0,Strong,Delhi
12,25,Female,99.0,Strong,Kolkata
78,11,Male,100.0,Mild,Bangalore
94,79,Male,NaN,Strong,Kolkata
37,55,Male,100.0,Mild,Kolkata


In [17]:
x_train.isnull().sum()

age       0
gender    0
fever     8
cough     0
city      0
dtype: int64

In [ ]:
# Adding simple imputer to fever col
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

# also the dataset 
x_test_fever=si.transform(x_test[['fever']])
x_train_fever.shape,x_test_fever.shape

((80, 1), (20, 1))

In [30]:
#x_train_fever

In [34]:
# Ordinalencoding -> cough
ore=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=ore.fit_transform(x_train[['cough']])

x_test_cough=ore.transform(x_test[['cough']])

x_train_cough.shape, x_test_cough.shape

((80, 1), (20, 1))

In [35]:
x_train_cough

array([[1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],

In [37]:
## OneHotEncoding -> gender, city
ohn=OneHotEncoder(drop='first',sparse_output=False)
x_train_city=ohn.fit_transform(x_train[['gender','city']])

# also the test data 
x_test_city=ohn.transform(x_test[['gender','city']])

x_train_city.shape, x_test_city.shape

((80, 4), (20, 4))

In [40]:
x_train['gender'].unique(), x_train['city'].unique()

(array(['Male', 'Female'], dtype=object),
 array(['Delhi', 'Kolkata', 'Bangalore', 'Mumbai'], dtype=object))

In [38]:
x_train_city

array([[1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],


In [41]:
x_train.head()

,age,gender,fever,cough,city
44,20,Male,102.0,Strong,Delhi
12,25,Female,99.0,Strong,Kolkata
78,11,Male,100.0,Mild,Bangalore
94,79,Male,NaN,Strong,Kolkata
37,55,Male,100.0,Mild,Kolkata


In [43]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [46]:
x_train_age=x_train.drop(columns=['gender','fever','cough','city'])

In [47]:
x_train_age

,age
44,20
12,25
78,11
94,79
37,55
...,...
58,23
21,73
49,44
64,42


In [48]:
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values

In [49]:
x_train_age

array([[20],
       [25],
       [11],
       [79],
       [55],
       [82],
       [20],
       [71],
       [10],
       [19],
       [19],
       [26],
       [72],
       [42],
       [51],
       [27],
       [34],
       [50],
       [13],
       [14],
       [56],
       [80],
       [64],
       [27],
       [14],
       [25],
       [83],
       [65],
       [33],
       [75],
       [49],
       [68],
       [51],
       [ 5],
       [19],
       [60],
       [75],
       [34],
       [23],
       [22],
       [82],
       [83],
       [31],
       [65],
       [83],
       [ 8],
       [81],
       [20],
       [16],
       [10],
       [47],
       [66],
       [24],
       [24],
       [34],
       [34],
       [18],
       [80],
       [38],
       [65],
       [59],
       [69],
       [74],
       [69],
       [ 5],
       [19],
       [82],
       [ 5],
       [47],
       [15],
       [51],
       [ 6],
       [40],
       [11],
       [69],
       [23],
       [73],

In [50]:
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

In [51]:
x_test_age

array([[12],
       [42],
       [70],
       [71],
       [49],
       [38],
       [73],
       [81],
       [65],
       [48],
       [64],
       [49],
       [16],
       [60],
       [46],
       [64],
       [84],
       [27],
       [12],
       [17]])

In [52]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [64]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,x_train_city,x_train_cough),axis=1)
x_test_transformed=np.concatenate((x_test_age,x_test_fever,x_test_city,x_test_cough),axis=1)

In [65]:
x_train_transformed.shape, x_test_transformed.shape

((80, 7), (20, 7))

In [66]:
x_train_transformed

array([[ 20.        , 102.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 25.        ,  99.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 11.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 79.        , 100.70833333,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 55.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 20.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 71.        , 100.70833333,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 10.        , 100.        ,   1.        ,   0.        ,
          0.    

In [67]:
x_train_transformed=pd.DataFrame(x_train_transformed)
x_train_transformed.head()

,0,1,2,3,4,5,6
0,20.0,102.000000,1.0,1.0,0.0,0.0,1.0
1,25.0,99.000000,0.0,0.0,1.0,0.0,1.0
2,11.0,100.000000,1.0,0.0,0.0,0.0,0.0
3,79.0,100.708333,1.0,0.0,1.0,0.0,1.0
4,55.0,100.000000,1.0,0.0,1.0,0.0,0.0


### column Transformer

In [68]:
from sklearn.compose import ColumnTransformer

In [73]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False, drop='first'),['gender','city'])
],remainder='passthrough')

In [74]:
x_train.head()

,age,gender,fever,cough,city
44,20,Male,102.0,Strong,Delhi
12,25,Female,99.0,Strong,Kolkata
78,11,Male,100.0,Mild,Bangalore
94,79,Male,NaN,Strong,Kolkata
37,55,Male,100.0,Mild,Kolkata


In [81]:
new_train_data=transformer.fit_transform(x_train)

In [82]:
new_train_data

array([[102.        ,   1.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  20.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [100.70833333,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  79.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  55.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [100.70833333,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.    

In [83]:
x_train.head()

,age,gender,fever,cough,city
44,20,Male,102.0,Strong,Delhi
12,25,Female,99.0,Strong,Kolkata
78,11,Male,100.0,Mild,Bangalore
94,79,Male,NaN,Strong,Kolkata
37,55,Male,100.0,Mild,Kolkata


In [80]:
new_test_data=transformer.transform(x_test)

In [78]:
new_test_data.shape

(20, 7)

In [79]:
new_test_data

array([[ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  70.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [100.70833333,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  38.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.    